imports:
    - { resource: easyadmin/ }

easy_admin:
    site_name: 'Tennis Club de Teyran'
    design:
        form_theme: '@EasyAdmin/form/bootstrap_4.html.twig'
        assets:
            css:
                - '../public/assets/css/admin.css'
                - 'https://use.fontawesome.com/releases/v5.6.1/css/all.css'
            js:
                - 'bundles/easyadmin/bootstrap-all.js'
            favicon: '/assets/img/favicon.ico'

        menu:
            - label: 'Actualité'
              icon: 'plus-circle'
              children:
                  - { entity: 'Article', label: 'Tous les articles', params: { action: 'list'}}
                  - { entity: 'Article', label: 'Créer un article', params: { action: 'new'}}
            - label: 'Agenda'
              icon: 'calendar'
              children:
                  - { entity: 'Event', label: 'Tous les évènements', params: { action: 'list'}}
                  - { entity: 'Event', label: 'Créer un évènement', params: { action: 'new'}}
            - label: 'Pages'
              icon: 'file'
              children:
                  - { entity: 'Page', label: 'Toutes les pages', params: { action: 'list'}}
                  - { entity: 'Page', label: 'Créer une page', params: { action: 'new'}}
            - label: 'Categories de pages'
              children:
                  - { entity: 'PageCategory', label: 'Tous les catégories', params: { action: 'list'}}
            - label: 'Utilisateurs'
              icon: 'user'
              children:
                  - { entity: 'User', label: 'Tous les utilisateurs', params: { action: 'list'}}

    formats:
        datetime: 'd/m/Y H:i:s'
    entities:
        Page:
            class: App\Entity\Page
        Article:
            class: App\Entity\Article
        Event:
            class: App\Entity\Event
        User:
            class: App\Entity\User
        PageCategory:
            class: App\Entity\PageCategory


