easy_admin:
    entities:
        Event:
            class: App\Entity\Event
            label: "Agenda"
            list:
                title: "Tous les évènements"
                max_results: 20
                actions:
                - { name: 'new', label: "Créer un évènement" }
                fields:
                - { property: 'title', label: "Titre de l'évènement"}
                - { property: 'eventDate', label: "Date de l'évènement"}
                - { property: 'createdAt', label: 'Créé le'}
                - { property: 'editedAt', label: 'Modifié le'}
                - { property: 'isPublished', label: 'Publication', type: 'boolean'}
                - { property: 'Lien en ligne', template: 'backEnd/event/getLinkOfEventOnline.html.twig'}
            search:
                title: "Résultat de la recherche"
                max_results: 20
            new:
                title: "Créer un évènement"
                fields:
                    - { type: 'group', columns: 8, label: 'Texte'}
                    - { property: 'title', label: "Titre de l'évènement"}
                    - { property: 'eventDate', label: "Date de l'évènement"}
                    - { property: 'content', label: 'Contenu', type: 'fos_ckeditor'}
                    - { type: 'group', columns: 4}
                    - { type: 'section', label: 'Publication'}
                    - { property: 'isPublished', label: 'Souhaitez-vous publier cette page ?'}
                    - { type: 'section', label: 'Illustration'}
                    - { property: 'imageFile', label: 'Photo', type: 'vich_image' }
            edit:
                title: "Modifier un évènement"
                actions:
                    - { name: '-delete' }
                fields:
                    - { type: 'group', columns: 8, label: 'Texte'}
                    - { property: 'title', label: "Titre de l'évènement"}
                    - { property: 'eventDate', label: "Date de l'évènement"}
                    - { property: 'content', label: 'Contenu', type: 'fos_ckeditor'}
                    - { type: 'group', columns: 4}
                    - { type: 'section', label: 'Publication'}
                    - { property: 'isPublished', label: 'Souhaitez-vous publier cette page ?'}
                    - { type: 'section', label: 'Illustration'}
                    - { property: 'imageFile', label: 'Photo', type: 'vich_image' }