easy_admin:
    entities:
        Page:
            class: App\Entity\Page
            label: "Pages"
            list:
                title: "Toutes les pages"
                max_results: 20
                fields:
                    - { property: 'title', label: 'Titre de la page'}
                    - { property: 'pageCategory', label: 'Catégorie'}
                    - { property: 'createdAt', label: 'Créée le'}
                    - { property: 'editedAt', label: 'Modifiée le'}
                    - { property: 'isPublished', label: 'Publication', type: 'boolean'}
                    - { property: 'Lien en ligne', template: 'backEnd/page/getLinkOfPageOnline.html.twig'}
            search:
                title: "Résultat de la recherche"
                max_results: 20
            new:
                title: "Créer une page"
                fields:
                    - { type: 'group', columns: 8, label: 'Texte'}
                    - { property: 'title', label: 'Titre de la page'}
                    - { property: 'pageCategory', label: 'Catégorie'}
                    - { property: 'content', label: 'Contenu', type: 'fos_ckeditor'}
                    - { type: 'group', columns: 4, label: 'Publication'}
                    - { property: 'isPublished', label: 'Souhaitez-vous publier cette page ?'}
            edit:
                title: "Modifier une page"
                actions:
                    # - { name: 'show', css_class: 'btn btn-primary' } TODO voir comment ajouter un bouton vers la
                    # page en ligne
                    - { name: '-delete' }
                fields:
                    - { type: 'group', columns: 8, label: 'Texte'}
                    - { property: 'title', label: 'Titre de la page'}
                    - { property: 'pageCategory', label: 'Catégorie'}
                    - { property: 'content', label: 'Contenu', type: 'fos_ckeditor'}
                    - { type: 'group', columns: 4, label: 'Publication'}
                    - { property: 'isPublished', label: 'Souhaitez-vous publier cette page ?'}
                    - { property: 'createdAt', label: 'Page créée le'}

            show:
                title: "Voir le contenu de la page"
                actions:
                    - { name: '-delete' }
                fields:
                    - { property: 'title', label: 'Titre de la page'}
                    - { property: 'pageCategory', label: 'Catégorie'}
                    - { property: 'content', label: 'Contenu'}
                    - { property: 'isPublished', label: 'Souhaitez-vous publier cette page ?'}
                    - { property: 'createdAt', label: 'Page créée le'}