easy_admin:
    entities:
        Page:
            class: App\Entity\Page
            label: "Pages"
            list:
                title: "Toutes les pages"
                max_results: 20
                actions:
                - { name: 'new', label: "Créer une page" }
                fields:
                    - { property: 'title', label: 'Titre de la page'}
                    - { property: 'pageCategory', label: 'Catégorie'}
                    - { property: 'createdAt', label: 'Créée le'}
                    - { property: 'editedAt', label: 'Modifiée le'}
                    - { property: 'isPublished', label: 'Publication', type: 'boolean'}
                    - { property: 'Lien en ligne', template: 'backEnd/page/getLinkOfPageOnline.html.twig'}
            search:
                title: "Résultat de la recherche"
                max_results: 20
            new:
                title: "Créer une page"
                fields:
                    - { type: 'group', columns: 8, label: 'Texte'}
                    - { property: 'title', label: 'Titre de la page'}
                    - { property: 'pageCategory', label: 'Catégorie'}
                    - { property: 'content', label: 'Contenu', type: 'fos_ckeditor'}
                    - { type: 'group', columns: 4}
                    - { type: 'section', label: 'Publication'}
                    - { property: 'isPublished', label: 'Souhaitez-vous publier cette page ?'}
                    - { type: 'section', label: 'Illustration'}
                    - { property: 'imageFile', label: 'Photo', type: 'vich_image' }

            edit:
                title: "Modifier une page"
                actions:
                    - { name: '-delete' }
                fields:
                    - { type: 'group', columns: 8, label: 'Texte'}
                    - { property: 'title', label: 'Titre de la page'}
                    - { property: 'createdAt', label: 'Créée le'}
                    - { property: 'pageCategory', label: 'Catégorie'}
                    - { property: 'content', label: 'Contenu', type: 'fos_ckeditor'}
                    - { type: 'group', columns: 4}
                    - { type: 'section', label: 'Publication'}
                    - { property: 'isPublished', label: 'Souhaitez-vous publier cette page ?'}
                    - { type: 'section', label: 'Illustration'}
                    - { property: 'imageFile', label: 'Photo', type: 'vich_image' }

            show:
                title: "Voir le contenu de la page"
                actions:
                    - { name: '-delete' }
                fields:
                    - { property: 'title', label: 'Titre de la page'}
                    - { property: 'pageCategory', label: 'Catégorie'}
                    - { property: 'content', label: 'Contenu'}
                    - { property: 'isPublished', label: 'Souhaitez-vous publier cette page ?'}
                    - { property: 'createdAt', label: 'Page créée le'}