easy_admin:
    entities:
        Page:
            class: App\Entity\Page
            label: "Pages"
            list:
                title: "Toutes les pages"
                max_results: 10
                fields:
                    - id
                    - { property: 'title', label: 'Titre de la page'}
                    - { property: 'pageCategory', label: 'Catégorie'}
                    - { property: 'createdAt', label: 'Créée le'}
                    - { property: 'editedAt', label: 'Modifiée le'}
                    - { property: 'user', label: 'Auteur'}
                    - { property: 'isPublished', label: 'Publication'}
            search:
                title: "Résultat de la recherche"
                fields:
                    - id
                    - { property: 'title', label: 'Titre de la page'}
                    - { property: 'pageCategory', label: 'Catégorie'}
                    - { property: 'createdAt', label: 'Créée le'}
                    - { property: 'editedAt', label: 'Modifiée le'}
                    - { property: 'user', label: 'Auteur'}
                    - { property: 'isPublished', label: 'Publication'}
            new:
                title: "Créer une page"
                fields:
                    - { type: 'group', columns: 8, label: 'Texte'}
                    - { property: 'title', label: 'Titre de la page'}
                    - { property: 'pageCategory', label: 'Catégorie'}
                    - { property: 'content', label: 'Contenu', type: 'fos_ckeditor'}
                    - { type: 'group', columns: 4, label: 'Publication'}
                    - { property: 'isPublished', label: 'Souhaitez-vous publier cette page ?'}
#                    // TODO Faire en sorte que le user soit enregistré d'office avec la session
            edit:
                title: "Modifier une page"
                actions: ['-delete']
                fields:
                    - { type: 'group', columns: 8, label: 'Texte'}
                    - { property: 'title', label: 'Titre de la page'}
                    - { property: 'pageCategory', label: 'Catégorie'}
                    - { property: 'content', label: 'Contenu', type: 'fos_ckeditor'}
                    - { type: 'group', columns: 4, label: 'Publication'}
                    - { property: 'isPublished', label: 'Souhaitez-vous publier cette page ?'}

