easy_admin:
    entities:
        User:
            class: App\Entity\User
            label: "Utilisateurs"
            list:
                title: "Tous les Utilisateurs"
                max_results: 20
                actions:
                    - { name: 'new', label: "Créer un utilisateur" }
                fields:
                    - { property: 'id', label: 'ID'}
                    - { property: 'username', label: 'Login'}
                    - { property: 'email', label: 'Email'}
                    - { property: 'roles', label: 'Role'}

            new:
                title: "Créer un utilisateur"
                fields:
                    - { property: 'username', label: 'Login'}
                    - { property: 'email', label: 'Email'}
                    -   property: 'plainPassword'
                        type: 'repeated'
                        type_options:
                            type: Symfony\Component\Form\Extension\Core\Type\PasswordType
                            first_options:
                                label: 'Mot de passe'
                            second_options:
                                label: 'Confirmez votre mot de passe'
                            required: true
                    -   property: 'roles'
                        label: 'Role'
                        type: 'choice'
                        type_options:
                             multiple: true
                             expanded: true
                             choices:
                                 'ROLE_USER': 'ROLE_USER'
                                 'ROLE_ADMIN': 'ROLE_ADMIN'

            edit:
                title: "Modifier un utilisateur"
                actions:
                    - { name: '-delete' }
                fields:
                    - { property: 'username', label: 'Login'}
                    - { property: 'email', label: 'Email'}
                    -   property: 'plainPassword'
                        type: 'repeated'
                        type_options:
                            type: Symfony\Component\Form\Extension\Core\Type\PasswordType
                            first_options:
                                label: 'Mot de passe'
                            second_options:
                                label: 'Confirmez votre mot de passe'
                            required: false
                    -   property: 'roles'
                        label: 'Role'
                        type: 'choice'
                        type_options:
                             multiple: true
                             expanded: true
                             choices:
                                 'ROLE_USER': 'ROLE_USER'
                                 'ROLE_ADMIN': 'ROLE_ADMIN'

